### ISSUE TITLE
[Feature request]: Support terminology codes

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/modos-api#103]
### Description

The metadata schema currently offers a very limited set of fields, some of which allow free text. To retain a simple schema while allowing richer information, we should support an annotation field (keyword, tags, codes, ...) allowing codes from selected ontologies / subclasses. The allowed set could differ depending on the class.

### Importance Level

Low

### Affected Components

api, cli, data schema

### Technical Requirements

We first need a way tool to browse codes by label, and auto-render label from uri.

### Acceptance criteria

Structured codes can be included to instances in modos:
* can be dynamically searched by label on data entry
* label can be displayed on inspection
* (only) code URI is persisted in metadata

**Comment by cmdoret** [comment]
Requirements:

* [ ] Update modos-schema to point to specific codes / ontologies
  + e.g. https://github.com/sdsc-ordes/modos-schema/issues/6
* [ ] embed github.com/sdsc-ordes/fuzon webserver in modos server
* [ ] (optional) fallback on pyfuzon for local use

**Comment by supermaxiste** [comment]
I left a code review and I will leave a beta-tester review as soon as I can make the system work.

**Comment by supermaxiste** [comment]
Left a deployment review and pre-approved the PR: only non-blocking comments 👍
