### ISSUE TITLE
[Bug]: ValueError: Unknown DataFormat enumeration code: mzTab

### ISSUE THREAD

**Issue by htmonkey** [sdsc-ordes/modos-api#113]
### What happened?

Tried to add a mzTab data entity...

data = model.DataEntity(id="metabolomics_1", name= "metabolomics_1", description = "untargeted metabolomics by FIA", data_format="mzTab", data_path = "metabo_1.mztab")

... but it rejects "mzTab"

### What system are you using?

Linux distribution

### Relevant log output

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 2
      1 # Generate a data element
----> 2 data = model.DataEntity(id="metabolomics_1", name= "metabolomics_1", description = "untargeted metabolomics by FIA", data_format="mzTab", data_path = "metabo_1.mztab")
      4 # Add element to modo
      5 modo.add_element(element = data, source_file="MM4 DATA.mztab")

File <string>:10, in __init__(self, id, name, description, data_path, data_format, has_sample, has_reference, **_kwargs)

File ~/modo-test/.pixi/envs/default/lib/python3.12/site-packages/modos_schema/datamodel/modos_schema.py:283, in DataEntity.__post_init__(self, *_, **kwargs)
    281     self.MissingRequiredField("data_format")
    282 if not isinstance(self.data_format, DataFormat):
--> 283     self.data_format = DataFormat(self.data_format)
    285 if not isinstance(self.has_sample, list):
    286     self.has_sample = [self.has_sample] if self.has_sample is not None else []

File ~/modo-test/.pixi/envs/default/lib/python3.12/site-packages/linkml_runtime/utils/enumerations.py:52, in EnumDefinitionImpl.__init__(self, code)
     50         self._code = code
     51 elif key not in self.__class__:
---> 52     raise ValueError(f"Unknown {self.__class__.__name__} enumeration code: {key}")
     53 elif isinstance_dt(code, "PermissibleValue"):
     54     if getattr(self, 'code', None):

ValueError: Unknown DataFormat enumeration code: mzTab
```

**Comment by cmdoret** [comment]
Hey @htmonkey, I should maybe have mentioned it, but the mzTab feature is not in a release yet as it's pretty rough, for now it's available on the main branch. As specified in the README, you can install it with:

```
pip install git+https://github.com/sdsc-ordes/modos-api.git@main
```

Does it work as expected for you if you install from main?

**Comment by cmdoret** [comment]
Just released 0.2.3 to avoid this problem with mztab https://github.com/sdsc-ordes/modos-api/releases/tag/v0.2.3

**Comment by htmonkey** [comment]
I can't get 0.2.3 from pypi.

**Comment by cmdoret** [comment]
Thanks! There was a CI bug, it's now available from pypi

**Comment by htmonkey** [comment]
I had additional problems with pyfuzon, but now it works. It looks really crude. Two questions:
1) is the mztab supposed to just be copied into the modo path OUTSIDE of the zarr?
2) the API should allow to recognize what elements exist in modo, type by type. How do I get the information without having to know how the mztab was named?

**Comment by cmdoret** [comment]
the terminal rendering of pyfuzon is indeed pretty crude; ideally the fuzzy search engine would be used for live feedback when typing in a form as part of a web UI.

1. The mztab is indeed copied outside the zarr hierarchy, as the zarr spec does not allow misc files in its herarchy. The zarr hierarchy has a corresponding node in `data` containing the metadata of embedded files, with a pointer to the filename. The current hierarchy could be improved (see notes [here](https://github.com/sdsc-ordes/modos-api/blob/docs/design/docs/design-notes.md)) and your suggestions are of course welcome.
2. From the CLI, you can show embedded files using `modos show --files`, from the API it would be `modo.list_files()`. If what you need is specifically the link between (zarr) identifier and file path, you could do `modo.show_contents('data') to get each DataEntity's metadata (including their file path).

Additionally, it is possible to query the metadata with SPARQL directly, so this would also work:

```python
>>> [r for r in modo.query('SELECT ?id ?path WHERE {?id a modos:DataEntity; modos:data_path ?path . }')]
[(rdflib.term.URIRef('file://ex/data/demo1'),
  rdflib.term.Literal('file://ex/demo1.cram'))]
```

This is very flexible, but of course not very user-friendly, so if you have a wishlist of helper methods you'd like us to add, we could easily add that.

**Comment by htmonkey** [comment]
I got it, thank you. The problem is not poor user-friendliness, but that you still lack fundamental functionalities that are at the core of MODOs (see "Goals"). I will close here and open a new issue.
