### ISSUE TITLE
Enable `extract_metadata()` to access remote cram files

### ISSUE THREAD

**Issue by almutlue** [sdsc-ordes/modos-api#27]
Currently, `modo.file_utils.extract_metadata` fails, if the cramfile is stored remotely, as it can not access the cramfile and its header. To enable this remote cramfiles should automatically be accessed via htsget server.

__Requirements__:

- [ ] change `extract_metadata` to access the cramfile header conditional on storage type
- [ ] access cram file header via htsget-server, if stored remotely

**Comment by cmdoret** [comment]
not a priority right now, this will come up again once the streaming is improved.
