### ISSUE TITLE
Use consistent element ids within modo

### ISSUE THREAD

**Issue by almutlue** [sdsc-ordes/modos-api#28]
Zarr groups are usually referred to with a prepending `/`. In line with this we sometimes use ids with a prepending `/` and sometimes not, e.g.:
```python
[k for k in modo.metadata.keys()]
['ex', '/sample/sample1, /reference/reference1', ...]

modo.list_samples()
['/sample/sample1']
```
At the same time we refer to element_ids within other elements without `/`:
```python
modo.metadata.values()
dict_values([{'@type': 'MODO',  'has_assay': ['assay/WGS_NA24143'], 'id': 'GIAB', ..'}, {'@type': 'Assay', 'has_data': ['data/NGS000000125'], 'has_sample': ['sample/NA24143'],..}])
```
Zarr itself seems to be flexible and maps both `/element_id` and `element_id` to the correct group, but within the modo api this leads to inconsistencies, e.g., `modo.knowledge_graph()` reports urls with`//`:

```python
[s for s in modo.knowledge_graph().subjects()]
[rdflib.term.URIRef('file://ex//assay/assay1'), rdflib.term.URIRef('file://ex//reference/reference1'),...]
```

**Comment by cmdoret** [comment]
In addition to this, there are inconsistencies w.r.t. inclusion of the type prefix

This is apparent in the output of `modo publish`: all subjects contain the type prefix `e.g. file://ex//reference/reference1`, but objects do not (e.g. `modos:has_reference <file://ex/reference>`. This can be seen in the zarr metadata as well, where values do not include the prefix.

This can cause breaking bugs, e.g. running `modo remove data/ex sample/sample1` removes `sample/sample1`, but not any of the links pointing to it.

Should we always include the type prefix when referring to other objects?

**Comment by almutlue** [comment]
I agree - we should always use the type prefix when referring to other objects. 
Currently, when specified via `--parent` (in cli `modo add`) or `part_of` (in api: `add_element()`) the full id including the type prefix is required, but when defined from the subjects side via `haspart` property we allow any id. 
Actually, we don't even check existence when specifying a relationship via `haspart` property. This is nice because we don't impose an order for adding elements, but it also means that `haspart` could currently point to non-existing elements. 

We could:
1. keep this, but check for long ids when elements are added 
2. restrict the order and only allow to define relationships to existing elements
What do you think @cmdoret? Any other ideas? Is there a preferred way of how a user should define element relationships?

**Comment by cmdoret** [comment]
I'd be tempted to say 2, but since we allow loading from yaml, order should not matter.
Checking for long ids sounds OK to me :+1:

**Comment by cmdoret** [comment]
Ntoe: the way the modo was build affects if long IDs are used.
`build_modo_from_file()` uses specifically [`update_haspart_id](https://github.com/sdsc-ordes/modo-api/blob/fb4c47af986f39566fc3741d4b756d32aae8558b/modo/helpers.py#L75). This is not the case with incremental addition of objects.
