### ISSUE TITLE
Automatically add cram index file 

### ISSUE THREAD

**Issue by almutlue** [sdsc-ordes/modos-api#41]
`modo.stream_cram()` expects a cram index file to exist in the modo object (local and remote streaming). Currently, we don't check for the index file and especially for remote cram files it can be cumbersome to add the cram index file. From a user 

There are differnet potential solutions:

1. __Automatically generate the index file__, if a cram file is added to a modo object. (+ easy for user, - may take time, - do we need make sure we use the correct reference for this?
2. Check for index file in same dir as cram file and __copy it together with cram into the modo__. If index does not exist warn/fail? 
3. Check for index in modo and warn user if it does not exist + __user function to copy/upload__ index file into modo

@cmdoret , @AssafSternberg do you have any preferences other ideas?

**Comment by cmdoret** [comment]
Solution 2+3 sounds more transparent to me:
```py
try:
  copy index and cram
except FileNotFoundError:
  raise FileNotFoundError(Missing index for cram)
```
I think this is the same behaviour as IGV
