### ISSUE TITLE
modos sync to update based on yaml file

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/modos-api#60]
Currently there is no simple way to update a modo: each change must be committed independently. And objects have to be deleted/recreated.

**Objective:** allow grouped updates based on an input file, incl renaming/editing objects. 

**Requirements:**
+ [ ] new command in CLI: `modos update dir [element_id]`
+ [ ] command adds new elements
+ [ ] command delete old elements
  + add + remove ~= rename
+ [ ] command edits existing elements

**Comment by almutlue** [comment]
__Question__: @cmdoret, I was looking into this and realized that there are different options for how to scope the `modos update` cli function. I'm not sure, which one we were intending here :
1. Update only explicit `element-id`, e.g. `modos update dir element_id`. This would not allow grouped updates though.
2. Update entire modo based on a yaml-file, similar to what `modo.from-file()` currently does when invoked for the second time.
3. A mix of both: Update specific element, if `--element-id` is specified (1) and update all if `--element-id` is not specified (2).

**Comment by cmdoret** [comment]
Option 2 sounds the most useful to me: `modos update config.yaml`

We may want helper flags for specific use cases, e.g. a `--no-remove` flag to only add/edit elements in the input config but not remove those that are in the modo but not in the config file.

As you said, we could also add an `--element-id` flag to target a specific element in the yaml.

The main goal being to reduce efforts, I think update from a yaml file is the most important (many elements at once). Targeting specific elements is less tedious to do manually and therefore can be considered secondary. Do you agree?

**Comment by almutlue** [comment]
yes, sounds good to me. I think option 2 plus a `--no-remove` flag has highest priority. 

I will see with `--element-id`, it could be nice, but I also agree with your comment on the streaming PR that to many arguments with different behaviours make the cli confusing.
